name: Publish MyGet Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Get the version from git tags
      id: get_version
      run: |
        TAG=$(git describe --tags --abbrev=0)
        VERSION=${TAG#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Pack the MyGet package
      run: dotnet pack --configuration Release --no-build --output ./nupkg -p:PackageVersion=${{ env.VERSION }}

    # - name: Publish the MyGet package
    #   env:
    #     MyGet_API_KEY: ${{ secrets.MyGet_API_KEY }}
    #   run: dotnet MyGet push ./nupkg/*.nupkg --api-key $MyGet_API_KEY --source https://api.MyGet.org/v3/index.json
